/**
 * Created by anna on 28.07.17.
 */
var locationOfImg = "../img/imgForMenu/imgForContainer/";
var arrayForbackground = [locationOfImg + '1.jpeg', locationOfImg + '2.jpeg',locationOfImg + '3.jpeg',locationOfImg + '4.jpeg',locationOfImg + '5.jpeg',locationOfImg + '6.jpeg',locationOfImg + '7.jpeg',locationOfImg + '8.jpeg',locationOfImg + '9.jpeg',];
var arrayOfH2 = ['Dessert with fruits', 'Bread from Gustoso', 'Pancakes with blueberries', 'Pasta with shrimp', 'DishNumber5', 'Coffee from Gustoso', 'Pie with nuts and apples', 'Deep tried potatoes', 'Strudel with apple'];
var arrayOfComposition = [];
var arrayForTime = ['10', '50', '20', '20', '30', '5', '25', '25', '45'];
var img = document.getElementById('back-images-container');
var size = 'no-repeat' + '' + 'center' + '' + 'center';
document.getElementById('1').onclick = function() {
    const count = 0;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('back-images-container');
    img.classList.remove('b2');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b1');
};
document.getElementById('2').onclick = function() {
    const count = 1;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b2');
};
document.getElementById('3').onclick = function() {
    const count = 2;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b2');
    img.classList.remove('b1');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b3');
};
document.getElementById('4').onclick = function() {
    const count = 3;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b2');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b4');
};
document.getElementById('5').onclick = function() {
    const count = 4;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b2');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b5');
};
document.getElementById('6').onclick = function() {
    const count = 5;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b2');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b6');
};
document.getElementById('7').onclick = function() {
    const count = 6;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b2');
    img.classList.remove('b8');
    img.classList.remove('b9');
    img.classList.add('b7');
};
document.getElementById('8').onclick = function() {
    const count = 7;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b2');
    img.classList.remove('b9');
    img.classList.add('b8');
};
document.getElementById('9').onclick = function() {
    const count = 8;
    document.getElementById('h2').innerHTML = '';
    document.getElementById('time').innerHTML = '';
    document.getElementById('h2').innerHTML = arrayOfH2[count];
    document.getElementById('time').innerHTML = arrayForTime[count];
    img.classList.remove('b1');
    img.classList.remove('b3');
    img.classList.remove('b4');
    img.classList.remove('b5');
    img.classList.remove('b6');
    img.classList.remove('b7');
    img.classList.remove('b8');
    img.classList.remove('b2');
    img.classList.add('b9');
};
